// File generated by FlutterFire CLI.
// This is a placeholder file. Run `flutterfire configure` to generate
// the actual Firebase options for your project.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase configuration.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6Tnr5VBXJ9a8RQ8Q980py7c0lOE3B2Q',
    appId: '1:804738161039:android:b4fcd3d96dbdb8078593fa',
    messagingSenderId: '804738161039',
    projectId: 'radi-right',
    storageBucket: 'radi-right.firebasestorage.app',
  );

  // Run `flutterfire configure` to generate the correct values.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpQGH643ajS0L6bNQVkjJlrf3eIyPwUlE',
    appId: '1:804738161039:ios:0aa07aaa504172a08593fa',
    messagingSenderId: '804738161039',
    projectId: 'radi-right',
    storageBucket: 'radi-right.firebasestorage.app',
    iosBundleId: 'com.zg0ul.radiright.radiRight',
  );

}